SpiderEnv-v0:
  n_envs: 1
  n_timesteps: 50000  # lo podés sobreescribir con -n si querés
  policy: "MlpPolicy"
  n_steps: 2048
  batch_size: 128
  gamma: 0.99
  learning_rate: 2.5e-4
  ent_coef: 0.0
  clip_range: 0.2
  n_epochs: 10
  gae_lambda: 0.95
  max_grad_norm: 0.5
  vf_coef: 0.5
  normalize: true